'use client';

import { FormEvent, useState, ChangeEvent, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { collection, addDoc, serverTimestamp, Timestamp } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { useAuth } from '../../context/AuthContext';
import { uploadMultipleImages, validateImageFile } from 'shared/storageService';
import { addCollectionItem } from 'shared/collectionService';
import { useToast } from '../../components/ToastProvider';
import { useCoinAutocomplete } from '../../hooks/useCoinAutocomplete';

// Keep your existing constants
const COUNTRIES = [
  'România', 'Germania', 'Franța', 'Italia', 'Spania', 'Regatul Unit', 'Austria', 'Elveția',
  'Rusia', 'Polonia', 'Ungaria', 'Cehia', 'Slovacia', 'Bulgaria', 'Serbia', 'Croația',
  'Grecia', 'Turcia', 'SUA', 'Canada', 'Australia', 'China', 'Japonia', 'India',
  'Brazilia', 'Argentina', 'Mexic', 'Africa de Sud', 'Egipt', 'Israel', 'Arabia Saudită'
];

const METALS = [
  'Aur', 'Argint', 'Cupru', 'Bronz', 'Oțel', 'Aluminiu', 'Platină', 'Paladiu',
  'Zinc', 'Nichel', 'Aliaj', 'Cupru-Nichel', 'Argint-Aur', 'Electrum'
];

const RARITIES = [
  { value: 'common', label: 'Comun' },
  { value: 'uncommon', label: 'Necomun' },
  { value: 'rare', label: 'Rar' },
  { value: 'very-rare', label: 'Foarte Rar' },
  { value: 'extremely-rare', label: 'Extrem de Rar' }
];

const GRADES = [
  'VF (Very Fine)', 'XF (Extremely Fine)', 'AU (Almost Uncirculated)', 'MS (Mint State)',
  'MS-60', 'MS-61', 'MS-62', 'MS-63', 'MS-64', 'MS-65', 'MS-66', 'MS-67', 'MS-68', 'MS-69', 'MS-70',
  'F (Fine)', 'VG (Very Good)', 'G (Good)', 'AG (About Good)', 'FA (Fair)', 'PR (Poor)',
  'UNC (Uncirculated)', 'BU (Brilliant Uncirculated)', 'Proof', 'Proof-like'
];

const CATEGORIES = [
  'Monede', 'Banknote', 'Medalii', 'Jetoane', 'Insigne', 'Ordine', 'Decorații', 'Altele'
];

export default function NewProductPage() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const { showToast } = useToast();
  
  // Use the autocomplete hook
  const {
    selectedDenomination,
    setSelectedDenomination,
    selectedYear,
    setSelectedYear,
    selectedMint,
    setSelectedMint,
    matchedCoin,
    availableDenominations,
    availableYears,
    availableMints,
    reset: resetAutocomplete,
  } = useCoinAutocomplete();

  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [price, setPrice] = useState('');
  const [country, setCountry] = useState('România'); // Default to România
  const [year, setYear] = useState('');
  const [era, setEra] = useState('');
  const [metal, setMetal] = useState('');
  const [denomination, setDenomination] = useState('');
  const [diameter, setDiameter] = useState('');
  const [weight, setWeight] = useState('');
  const [mintLocation, setMintLocation] = useState('');
  const [rarity, setRarity] = useState('');
  const [grade, setGrade] = useState('');
  const [files, setFiles] = useState<File[]>([]);
  const [listingType, setListingType] = useState<'direct' | 'auction'>('direct');
  const [reservePrice, setReservePrice] = useState('');
  const [minAcceptPrice, setMinAcceptPrice] = useState('');
  const [buyNowPrice, setBuyNowPrice] = useState('');
  const [auctionEndTime, setAuctionEndTime] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [useAutocomplete, setUseAutocomplete] = useState(true);
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);

  // Auto-fill fields when matched coin is found
  useEffect(() => {
    if (matchedCoin && useAutocomplete) {
      setYear(String(matchedCoin.issue_year) || '');
      setEra(matchedCoin.era || '');
      setDenomination(matchedCoin.face_value || '');
      setMetal(matchedCoin.metal || '');
      setDiameter(matchedCoin.diameter || '');
      setWeight(matchedCoin.weight || '');
      setMintLocation(matchedCoin.mint_or_theme || '');

      // Auto-generate name if it was auto-generated or empty
      if (isNameAutoGenerated || !name.trim()) {
        setName(`${matchedCoin.face_value} ${matchedCoin.issue_year} - ${matchedCoin.mint_or_theme}`);
        setIsNameAutoGenerated(true);
      }
    }
  }, [matchedCoin, useAutocomplete, isNameAutoGenerated, name]);

  useEffect(() => {
    if (!loading && !user) {
      router.replace('/login');
    }
  }, [loading, user, router]);

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const fileList = e.target.files;
    if (!fileList) {
      setFiles([]);
      return;
    }

    const selected: File[] = [];
    for (let i = 0; i < fileList.length; i++) {
      const file = fileList.item(i);
      if (!file) continue;
      const { valid, error } = validateImageFile(file);
      if (!valid) {
        showToast({
          type: 'error',
          title: 'Eroare la încărcarea imaginilor',
          message: error ?? 'Fișier invalid.',
        });
        continue;
      }
      selected.push(file);
    }
    setFiles(selected);
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!user) {
      showToast({
        type: 'error',
        title: 'Autentificare necesară',
        message: 'Trebuie să fii autentificat pentru a adăuga un produs.',
      });
      router.push('/login');
      return;
    }

    if (!name.trim() || !description.trim()) {
      showToast({
        type: 'error',
        title: 'Câmpuri obligatorii',
        message: 'Numele și descrierea sunt obligatorii.',
      });
      return;
    }

    const numericPrice = Number(price);
    if (!Number.isFinite(numericPrice) || numericPrice <= 0) {
      showToast({
        type: 'error',
        title: 'Preț invalid',
        message: 'Introdu un preț valid mai mare decât 0.',
      });
      return;
    }

    if (listingType === 'auction') {
      const numericReserve = Number(reservePrice || price);
      if (!Number.isFinite(numericReserve) || numericReserve <= 0) {
        showToast({
          type: 'error',
          title: 'Preț de start invalid',
          message: 'Introdu un preț de start valid mai mare decât 0.',
        });
        return;
      }

      const numericMinAccept = Number(minAcceptPrice || numericReserve);
      if (!Number.isFinite(numericMinAccept) || numericMinAccept <= 0) {
        showToast({
          type: 'error',
          title: 'Preț minim acceptat invalid',
          message: 'Introdu un preț minim acceptat valid mai mare decât 0.',
        });
        return;
      }
      if (numericMinAccept < numericReserve) {
        showToast({
          type: 'error',
          title: 'Preț minim prea mic',
          message: 'Prețul minim acceptat trebuie să fie cel puțin egal cu prețul de start.',
        });
        return;
      }

      if (buyNowPrice) {
        const numericBuyNow = Number(buyNowPrice);
        if (!Number.isFinite(numericBuyNow) || numericBuyNow <= 0) {
          showToast({
            type: 'error',
            title: 'Preț "Cumpără acum" invalid',
            message: 'Introdu un preț "Cumpără acum" valid mai mare decât 0.',
          });
          return;
        }
        if (numericBuyNow < numericMinAccept) {
          showToast({
            type: 'error',
            title: 'Preț "Cumpără acum" prea mic',
            message: 'Prețul "Cumpără acum" trebuie să fie cel puțin egal cu prețul minim acceptat.',
          });
          return;
        }
      }

      if (!auctionEndTime) {
        showToast({
          type: 'error',
          title: 'Dată de încheiere lipsă',
          message: 'Selectează data și ora de încheiere a licitației.',
        });
        return;
      }
      const end = new Date(auctionEndTime);
      if (Number.isNaN(end.getTime()) || end <= new Date()) {
        showToast({
          type: 'error',
          title: 'Dată de încheiere invalidă',
          message: 'Data de încheiere trebuie să fie în viitor.',
        });
        return;
      }
    }

    try {
      setSubmitting(true);

      let imageUrls: string[] = [];
      if (files.length > 0) {
        imageUrls = await uploadMultipleImages(files, `products/${user.uid}`);
      }

      const productRef = await addDoc(collection(db, 'products'), {
        name: name.trim(),
        description: description.trim(),
        images: imageUrls,
        price: numericPrice,
        ownerId: user.uid,
        status: 'pending',
        country: country || null,
        year: year ? Number(year) : null,
        era: era || null,
        metal: metal || null,
        denomination: denomination || null,
        diameter: diameter || null,
        weight: weight || null,
        mintLocation: mintLocation || null,
        rarity: rarity || null,
        grade: grade || null,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      try {
        await addCollectionItem(user.uid, {
          name: name.trim(),
          description: description.trim(),
          images: imageUrls,
          country: country || undefined,
          year: year ? Number(year) : undefined,
          era: era || undefined,
          metal: metal || undefined,
          denomination: denomination || undefined,
          rarity: rarity || undefined,
          grade: grade || undefined,
          acquisitionPrice: numericPrice,
          currentValue: numericPrice,
          notes: 'Articol creat în magazin',
          tags: ['listare-magazin'],
        });
      } catch (err) {
        console.error('Failed to add product to collection', err);
      }

      if (listingType === 'auction') {
        const reserve = reservePrice ? Number(reservePrice) : numericPrice;
        const minAccept = minAcceptPrice ? Number(minAcceptPrice) : reserve;
        const buyNow = buyNowPrice ? Number(buyNowPrice) : null;
        const end = new Date(auctionEndTime);
        await addDoc(collection(db, 'auctions'), {
          productId: productRef.id,
          startTime: Timestamp.fromDate(new Date()),
          endTime: Timestamp.fromDate(end),
          reservePrice: reserve,
          minAcceptPrice: minAccept,
          buyNowPrice: buyNow,
          buyNowUsed: false,
          currentBid: null,
          currentBidderId: null,
          status: 'pending',
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }

      showToast({
        type: 'success',
        title: listingType === 'auction' ? 'Licitație trimisă spre aprobare' : 'Produs trimis spre aprobare',
        message: listingType === 'auction'
          ? 'Licitația a fost trimisă spre aprobare. Un administrator o va verifica înainte să apară public.'
          : 'Produsul a fost trimis spre aprobare. Un administrator îl va verifica înainte să apară public.',
      });

      router.push('/dashboard');
    } catch (err: any) {
      console.error('Failed to create product/auction', err);
      showToast({
        type: 'error',
        title: 'Eroare la salvare',
        message: err?.message || 'A apărut o eroare la salvarea produsului.',
      });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading || !user) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gold-500" />
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-2xl mx-auto bg-navy-900/80 border border-gold-500/40 rounded-2xl p-6 shadow-[0_18px_55px_rgba(0,0,0,0.85)]">
        <h1 className="text-2xl font-bold text-white mb-4">Adaugă un produs</h1>
        
        {/* Toggle for Romanian Coins */}
        <div className="mb-6 p-4 bg-navy-800/50 rounded-lg border border-gold-500/20">
          <label className="flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={useAutocomplete && country === 'România'}
              onChange={(e) => {
                setUseAutocomplete(e.target.checked);
                if (e.target.checked) {
                  setCountry('România');
                } else {
                  resetAutocomplete();
                }
              }}
              className="w-4 h-4 text-gold-500 bg-navy-700 border-gold-500/40 rounded focus:ring-gold-500/50"
            />
            <span className="ml-3 text-sm text-slate-200">
              Folosește asistentul pentru monede românești
            </span>
          </label>
          <p className="mt-2 text-xs text-slate-400">
            Activează pentru auto-completare bazată pe baza de date de monede românești
          </p>
        </div>

        {/* Romanian Coin Autocomplete Section */}
        {useAutocomplete && country === 'România' && (
          <div className="mb-6 p-4 bg-gradient-to-r from-gold-500/10 to-gold-600/10 rounded-lg border border-gold-500/30 space-y-4">
            <h3 className="text-lg font-semibold text-gold-400 mb-3">🪙 Asistent Monede Românești</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Denomination Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Valoare nominală *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={selectedDenomination}
                  onChange={(e) => setSelectedDenomination(e.target.value)}
                >
                  <option value="">Selectează valoarea</option>
                  {availableDenominations.map((denomination) => (
                    <option key={denomination} value={denomination}>{denomination}</option>
                  ))}
                </select>
              </div>

              {/* Year Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  An *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(e.target.value)}
                  disabled={!selectedDenomination}
                >
                  <option value="">Selectează anul</option>
                  {availableYears.map((year) => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </select>
              </div>

              {/* Mint Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Monetărie / Temă *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
                  value={selectedMint}
                  onChange={(e) => setSelectedMint(e.target.value)}
                  disabled={!selectedYear}
                >
                  <option value="">Selectează monetăria</option>
                  {availableMints.map((mint) => (
                    <option key={mint} value={mint}>{mint}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Matched Coin Preview */}
            {matchedCoin && (
              <div className="mt-4 p-3 bg-navy-800/60 rounded-lg border border-gold-500/20">
                <div className="flex items-center mb-2">
                  <svg className="w-5 h-5 text-green-400 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0zm-8-3a1 1 0 11-2 0 1 1 0 012 0zm0 8a1 1 0 100-2 1 1 0 000 2z" />
                  </svg>
                  <span className="text-sm font-semibold text-green-400">Monedă găsită în baza de date!</span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-xs text-slate-300">
                  <div><span className="text-slate-400">Diametru:</span> {matchedCoin.diameter}</div>
                  <div><span className="text-slate-400">Greutate:</span> {matchedCoin.weight}</div>
                  <div><span className="text-slate-400">Metal:</span> {matchedCoin.metal}</div>
                  <div><span className="text-slate-400">Monetărie:</span> {matchedCoin.mint_or_theme}</div>
                </div>
              </div>
            )}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Listing Type Selection */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-slate-200 mb-3">
              Tip vânzare *
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <label className={`relative cursor-pointer rounded-lg border-2 p-4 transition-all ${
                listingType === 'direct'
                  ? 'border-gold-500/40 bg-navy-800/50 text-slate-300'
                  : 'border-gold-400 bg-gold-400/10 text-gold-300 hover:border-gold-500/60'
              }`}>
                <input
                  type="radio"
                  name="listingType"
                  value="direct"
                  checked={listingType === 'direct'}
                  onChange={(e) => setListingType(e.target.value as 'direct' | 'auction')}
                  className="sr-only"
                />
                <div className="text-center">
                  <div className={`w-12 h-12 mx-auto mb-2 rounded-full flex items-center justify-center ${
                    listingType === 'direct' ? 'bg-navy-700 text-gold-400' : 'bg-gold-400 text-navy-900'
                  }`}>
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1" />
                    </svg>
                  </div>
                  <h3 className="font-semibold text-lg mb-1">Vând direct</h3>
                  <p className="text-sm opacity-80">Preț fix, cumpărare imediată</p>
                </div>
              </label>

              <label className={`relative cursor-pointer rounded-lg border-2 p-4 transition-all ${
                listingType === 'auction'
                  ? 'border-gold-500/40 bg-navy-800/50 text-slate-300'
                  : 'border-gold-400 bg-gold-400/10 text-gold-300 hover:border-gold-500/60'
              }`}>
                <input
                  type="radio"
                  name="listingType"
                  value="auction"
                  checked={listingType === 'auction'}
                  onChange={(e) => setListingType(e.target.value as 'direct' | 'auction')}
                  className="sr-only"
                />
                <div className="text-center">
                  <div className={`w-12 h-12 mx-auto mb-2 rounded-full flex items-center justify-center ${
                    listingType === 'auction' ? 'bg-navy-700 text-gold-400' : 'bg-gold-400 text-navy-900'
                  }`}>
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                    </svg>
                  </div>
                  <h3 className="font-semibold text-lg mb-1">Pun la licitație</h3>
                  <p className="text-sm opacity-80">Licitație cu mai mulți participanți</p>
                </div>
              </label>
            </div>
          </div>

          {/* Name Input */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Nume produs *
            </label>
            <input
              type="text"
              className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setIsNameAutoGenerated(false);
              }}
              placeholder={matchedCoin ? `Ex: ${matchedCoin.face_value} ${matchedCoin.issue_year}` : ''}
              required
            />
          </div>

          {/* Description Input */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Descriere *
            </label>
            <textarea
              className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              required
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Price */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Preț fix (RON) *
              </label>
              <input
                type="number"
                min="0"
                step="0.01"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={price}
                onChange={(e) => setPrice(e.target.value)}
                required
              />
            </div>

            {/* Country */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Țara *
              </label>
              <select
                className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                value={country}
                onChange={(e) => {
                  setCountry(e.target.value);
                  if (e.target.value !== 'România') {
                    setUseAutocomplete(false);
                    resetAutocomplete();
                  }
                }}
              >
                <option value="">Selectează țara</option>
                {COUNTRIES.map(c => (
                  <option key={c} value={c}>{c}</option>
                ))}
              </select>
            </div>

            {/* Year (Manual or Auto-filled) */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                An {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="number"
                min="0"
                max="2100"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={year}
                onChange={(e) => setYear(e.target.value)}
                placeholder="Ex: 2024"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Era (Manual or Auto-filled) */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Epocă {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={era}
                onChange={(e) => setEra(e.target.value)}
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Metal (Auto-filled or Manual) */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Metal {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={metal}
                onChange={(e) => setMetal(e.target.value)}
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Denomination */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Denominație {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={denomination}
                onChange={(e) => setDenomination(e.target.value)}
                placeholder="Ex: 1 Leu"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Diameter */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Diametru {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={diameter}
                onChange={(e) => setDiameter(e.target.value)}
                placeholder="Ex: 23 mm"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Weight */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Greutate {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={weight}
                onChange={(e) => setWeight(e.target.value)}
                placeholder="Ex: 5 g"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Mint Location */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Monetărie / Temă {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="text"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={mintLocation}
                onChange={(e) => setMintLocation(e.target.value)}
                placeholder="Ex: Bucharest"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Rarity */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Raritate
              </label>
              <select
                className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                value={rarity}
                onChange={(e) => setRarity(e.target.value)}
              >
                <option value="">Selectează raritatea</option>
                {RARITIES.map(r => (
                  <option key={r.value} value={r.value}>{r.label}</option>
                ))}
              </select>
            </div>

            {/* Grade */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Grad / stare
              </label>
              <select
                className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                value={grade}
                onChange={(e) => setGrade(e.target.value)}
              >
                <option value="">Selectează gradul</option>
                {GRADES.map(g => (
                  <option key={g} value={g}>{g}</option>
                ))}
              </select>
            </div>
          </div>

          {/* Images */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Imagini
            </label>
            <input
              type="file"
              multiple
              accept="image/*"
              onChange={handleFileChange}
              className="block w-full text-sm text-slate-200 file:mr-3 file:rounded-full file:border-0 file:bg-gold-500 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-navy-900 hover:file:bg-gold-400"
            />
            {files.length > 0 && (
              <p className="mt-1 text-xs text-slate-300">
                {files.length} imagine{files.length > 1 ? 'i' : ''} selectate
              </p>
            )}
          </div>

          {/* Auction fields (if applicable) */}
          {listingType === 'auction' && (
            <div className="mt-4 border-t border-gold-500/30 pt-4 space-y-3">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț de start licitație (RON)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={reservePrice}
                    onChange={(e) => setReservePrice(e.target.value)}
                    placeholder={price || 'Ex: 10.00'}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț minim acceptat (doar pentru tine) (RON)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={minAcceptPrice}
                    onChange={(e) => setMinAcceptPrice(e.target.value)}
                    placeholder={reservePrice || price || 'Ex: 100.00'}
                  />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț "Cumpără acum" (RON, opțional)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={buyNowPrice}
                    onChange={(e) => setBuyNowPrice(e.target.value)}
                    placeholder={minAcceptPrice || reservePrice || price || 'Ex: 150.00'}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Dată & oră de încheiere *
                  </label>
                  <input
                    type="datetime-local"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={auctionEndTime}
                    onChange={(e) => setAuctionEndTime(e.target.value)}
                    required
                  />
                </div>
              </div>
            </div>
          )}

          {/* Submit Button */}
          <div className="pt-2 flex justify-end">
            <button
              type="submit"
              disabled={submitting}
              className="inline-flex items-center justify-center rounded-full bg-[#e7b73c] px-6 py-2 text-sm font-semibold text-[#000940] shadow-lg shadow-[0_0_25px_rgba(231,183,60,0.7)] transition hover:bg-[#f0c955] disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {submitting ? 'Se salvează...' : 'Trimite spre aprobare'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}