"use client";

export const dynamic = 'force-dynamic';

import { FormEvent, useState, ChangeEvent, useEffect, Suspense } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { collection, addDoc, serverTimestamp, Timestamp, doc, getDoc, updateDoc } from 'firebase/firestore';
import { db } from '../../lib/firebase';
import { useAuth } from '../../context/AuthContext';
import { uploadMultipleImages, uploadVideo, validateImageFile } from 'shared/storageService';
import { addCollectionItem, getCollectionItem, updateCollectionItem } from 'shared/collectionService';
import { useToast } from '../../components/ToastProvider';
import { useCoinAutocomplete } from '../../hooks/useCoinAutocomplete';

// Keep your existing constants
const COUNTRIES = [
  'România', 'Germania', 'Franța', 'Italia', 'Spania', 'Regatul Unit', 'Austria', 'Elveția',
  'Rusia', 'Polonia', 'Ungaria', 'Cehia', 'Slovacia', 'Bulgaria', 'Serbia', 'Croația',
  'Grecia', 'Turcia', 'SUA', 'Canada', 'Australia', 'China', 'Japonia', 'India',
  'Brazilia', 'Argentina', 'Mexic', 'Africa de Sud', 'Egipt', 'Israel', 'Arabia Saudită'
];

const METALS = [
  'Aur', 'Argint', 'Cupru', 'Bronz', 'Oțel', 'Aluminiu', 'Platină', 'Paladiu',
  'Zinc', 'Nichel', 'Aliaj', 'Cupru-Nichel', 'Argint-Aur', 'Electrum'
];

const RARITIES = [
  { value: 'common', label: 'Comun' },
  { value: 'uncommon', label: 'Necomun' },
  { value: 'rare', label: 'Rar' },
  { value: 'very-rare', label: 'Foarte Rar' },
  { value: 'extremely-rare', label: 'Extrem de Rar' }
];

const GRADES = [
  'VF (Very Fine)', 'XF (Extremely Fine)', 'AU (Almost Uncirculated)', 'MS (Mint State)',
  'MS-60', 'MS-61', 'MS-62', 'MS-63', 'MS-64', 'MS-65', 'MS-66', 'MS-67', 'MS-68', 'MS-69', 'MS-70',
  'F (Fine)', 'VG (Very Good)', 'G (Good)', 'AG (About Good)', 'FA (Fair)', 'PR (Poor)',
  'UNC (Uncirculated)', 'BU (Brilliant Uncirculated)', 'Proof', 'Proof-like'
];

const CERTIFICATION_COMPANIES = [
  { value: 'NGC', label: 'NGC (Numismatic Guaranty Corporation)' },
  { value: 'PCGS', label: 'PCGS (Professional Coin Grading Service)' }
];

const NGC_GRADES = [
  'NGCX',
  '70', '69', '68', '67', '65', '66', '64', '63', '62', '61', '60', '58', '55', '53', '50', '45', '40', '35', '30', '25', '20', '15', '10', '8', '6', '4', '3', '2', '1',
  'NGC Ancients',
  'NGC Details',
  'Other'
];

const PCGS_GRADES = [
  '70', '69', '68', '67', '65', '66', '64', '63', '62', '61', '60', '58', '55', '53', '50', '45', '40', '35', '30', '25', '20', '15', '10', '8', '6', '4', '3', '2', '1',
  'PCGS Ancients',
  'PCGS Details',
  'Other'
];

const CATEGORIES = [
  'Monede', 'Bancnote'
];

function NewProductPageContent() {
  const { user, loading } = useAuth();
  const router = useRouter();
  const { showToast } = useToast();
  const searchParams = useSearchParams();
  const [collectionItem, setCollectionItem] = useState<any>(null);
  const [loadingCollectionItem, setLoadingCollectionItem] = useState(false);
  
  // Use the autocomplete hook
  const {
    selectedDenomination,
    setSelectedDenomination,
    selectedYear,
    setSelectedYear,
    selectedMint,
    setSelectedMint,
    matchedCoin,
    availableDenominations,
    availableYears,
    availableMints,
    reset: resetAutocomplete,
  } = useCoinAutocomplete();

  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [price, setPrice] = useState('');
  const [category, setCategory] = useState('Monede'); // Default to Monede
  const [country, setCountry] = useState('România'); // Default to România
  const [year, setYear] = useState('');
  const [era, setEra] = useState('');
  const [metal, setMetal] = useState('');
  const [denomination, setDenomination] = useState('');
  const [diameter, setDiameter] = useState('');
  const [weight, setWeight] = useState('');
  const [mintLocation, setMintLocation] = useState('');
  const [rarity, setRarity] = useState('');
  const [grade, setGrade] = useState('');
  const [files, setFiles] = useState<File[]>([]);
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [listingType, setListingType] = useState<'direct' | 'auction'>('direct');
  const [reservePrice, setReservePrice] = useState('');
  const [minAcceptPrice, setMinAcceptPrice] = useState('');
  const [buyNowPrice, setBuyNowPrice] = useState('');
  const [auctionDuration, setAuctionDuration] = useState<number>(3);
  const [submitting, setSubmitting] = useState(false);
  const [compressingImages, setCompressingImages] = useState(false);
  const [useAutocomplete, setUseAutocomplete] = useState(true);
  const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);
  const [editingProduct, setEditingProduct] = useState<any>(null);
  const [loadingEdit, setLoadingEdit] = useState(false);

  // Certification fields
  const [hasCertification, setHasCertification] = useState(false);
  const [certificationCompany, setCertificationCompany] = useState('NGC');
  const [certificationCode, setCertificationCode] = useState('');
  const [certificationGrade, setCertificationGrade] = useState('');

  // Offer settings
  const [acceptsOffers, setAcceptsOffers] = useState(true);

  // NOTE:
  // Rely on AuthContext role flags instead of re-querying via shared/adminService.
  // This avoids transient false negatives when dynamic imports or Firestore reads fail.
  const isPrivilegedUser = Boolean(user?.isAdmin || user?.isSuperAdmin);

  // Permission: only verified users or admins/superadmins can upload product videos
  const canUploadVideo = !!user && ((user as any).idVerificationStatus === 'verified' || isPrivilegedUser);

  // Load collection item if provided, or edit existing product
  useEffect(() => {
    const collectionItemId = searchParams.get('collectionItemId');
    const listingTypeParam = searchParams.get('listingType');
    const editProductId = searchParams.get('edit');

    if (editProductId && user?.uid) {
      const loadProductForEdit = async () => {
        setLoadingEdit(true);
        try {
          const { getProductById } = await import('shared/adminService');
          const product = await getProductById(editProductId);

          if (!product) {
            showToast({
              type: 'error',
              title: 'Piesă negăsită',
              message: 'Piesa pe care încerci să o editezi nu există.',
            });
            router.push('/dashboard');
            return;
          }

          const canEditAny = Boolean(user?.isAdmin || user?.isSuperAdmin);

          console.log('Permission check:', {
            userId: user.uid,
            productOwnerId: product.ownerId,
            userRole: user.role,
            isAdmin: user.isAdmin,
            isSuperAdmin: user.isSuperAdmin,
            canEditAny,
            ownsProduct: product.ownerId === user.uid
          });

          // Check if user owns the product or is privileged
          if (product.ownerId !== user.uid && !canEditAny) {
            showToast({
              type: 'error',
              title: 'Acces interzis',
              message: 'Nu poți edita o piesă care nu îți aparține.',
            });
            router.push('/dashboard');
            return;
          }

          setEditingProduct(product);

          // Populate form with product data
          setName(product.name || '');
          setDescription(product.description || '');
          setCategory(product.category || 'Monede');
          setCountry(product.country || 'România');
          setYear(product.year ? String(product.year) : '');
          setEra(product.era || '');
          setMetal(product.metal || '');
          setDenomination(product.denomination || '');
          setGrade(product.grade || '');
          setRarity(product.rarity || '');
          setDiameter(product.diameter ? String(product.diameter) : '');
          setWeight(product.weight ? String(product.weight) : '');
          setMintLocation(product.mintMark || '');
          setPrice(product.price ? String(product.price) : '');
          setListingType(product.listingType || 'direct');
          setHasCertification(product.hasCertification || false);
          setCertificationCompany(product.certificationCompany || 'NGC');
          setCertificationCode(product.certificationCode || '');
          setCertificationGrade(product.certificationGrade || '');
          setAcceptsOffers(product.acceptsOffers !== false);

          // If it's an auction, we might need to load auction data too
          // For now, we'll handle basic product editing

        } catch (error) {
          console.error('Failed to load product for editing:', error);
          showToast({
            type: 'error',
            title: 'Eroare la încărcarea piesei',
            message: 'Nu s-a putut încărca piesa pentru editare.',
          });
          router.push('/dashboard');
          return;
        } finally {
          setLoadingEdit(false);
        }
      };

      loadProductForEdit();
    }

    if (collectionItemId && user?.uid) {
      setLoadingCollectionItem(true);
      getCollectionItem(user.uid, collectionItemId)
        .then(async (item) => {
          if (item) {
            setCollectionItem(item);
            // Pre-fill form with collection item data
            setName(item.name || '');
            setDescription(item.description || '');
            setCategory(item.category || 'Monede');
            setCountry(item.country || 'România');
            setYear(item.year ? String(item.year) : '');
            setEra(item.era || '');
            setMetal(item.metal || '');
            setDenomination(item.denomination || '');
            setGrade(item.grade || '');
            setRarity(item.rarity || '');
            setDiameter(item.diameter ? String(item.diameter) : '');
            setWeight(item.weight ? String(item.weight) : '');
            setMintLocation(item.mintMark || '');

            // Handle pricing for Monetaria Statului products
            if (item.tags?.includes('monetaria-statului')) {
              try {
                // Fetch price from monetaria-data.json
                const response = await fetch('/monetaria-data.json');
                if (response.ok) {
                  const data = await response.json();
                  const monetariaProduct = data.products.find((p: any) => p.product_id === item.id);
                  if (monetariaProduct && monetariaProduct.price) {
                    // Parse price using Romanian number format (dot as thousand separator)
                    const parsedPrice = monetariaProduct.price.replace(/[^\d.,]/g, '');
                    // Handle Romanian format: remove dots (thousand separators) and replace comma with dot
                    const cleanedPrice = parsedPrice.replace(/\./g, '').replace(',', '.');
                    const numericPrice = parseFloat(cleanedPrice);
                    if (!isNaN(numericPrice)) {
                      // Convert RON to EUR
                      const RON_TO_EUR_RATE = 4.97;
                      const eurPrice = numericPrice / RON_TO_EUR_RATE;
                      setPrice(String(Math.round(eurPrice)));
                    }
                  }
                }
              } catch (error) {
                console.error('Failed to fetch monetaria price:', error);
                // Fallback to current value
                if (item.currentValue) {
                  if (item.tags?.includes('monetaria-statului')) {
                    // Convert RON to EUR
                    const eurPrice = item.currentValue / 4.97;
                    setPrice(String(Math.round(eurPrice)));
                  } else {
                    setPrice(String(item.currentValue));
                  }
                }
              }
            } else {
              // Set price to current value for regular collection items
              if (item.currentValue && item.currentValue > 0) {
                setPrice(String(item.currentValue));
              }
            }

            // Set listing type from URL param
            if (listingTypeParam === 'auction') {
              setListingType('auction');
            } else {
              setListingType('direct');
            }
          }
        })
        .catch((error) => {
          console.error('Failed to load collection item:', error);
          showToast({
            type: 'error',
            title: 'Eroare',
            message: 'Nu s-a putut încărca piesa din colecție.',
          });
        })
        .finally(() => {
          setLoadingCollectionItem(false);
        });
    }
  }, [searchParams, user?.uid, showToast]);

  // Auto-fill fields when matched coin is found
  useEffect(() => {
    if (matchedCoin && useAutocomplete) {
      setYear(String(matchedCoin.issue_year) || '');
      setEra(matchedCoin.era || '');
      setDenomination(matchedCoin.face_value || '');
      setMetal(matchedCoin.metal || '');
      setDiameter(matchedCoin.diameter || '');
      setWeight(matchedCoin.weight || '');
      setMintLocation(matchedCoin.mint_or_theme || '');

      // Auto-generate name if it was auto-generated or empty
      if (isNameAutoGenerated || !name.trim()) {
        setName(`${matchedCoin.face_value} ${matchedCoin.issue_year} - ${matchedCoin.mint_or_theme}`);
        setIsNameAutoGenerated(true);
      }
    }
  }, [matchedCoin, useAutocomplete, isNameAutoGenerated, name]);

  useEffect(() => {
    if (!loading && !user) {
      router.replace('/login');
    }
  }, [loading, user, router]);

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    const fileList = e.target.files;
    if (!fileList) {
      console.log('No files selected');
      return;
    }

    console.log(`File input triggered with ${fileList.length} files`);
    const selected: File[] = [];
    for (let i = 0; i < fileList.length; i++) {
      const file = fileList.item(i);
      if (!file) continue;

      console.log(`Processing file: ${file.name} (${file.size} bytes)`);

      // Check for duplicates based on name and size
      const isDuplicate = files.some(existingFile =>
        existingFile.name === file.name && existingFile.size === file.size
      );
      if (isDuplicate) {
        console.log(`Skipping duplicate file: ${file.name}`);
        continue; // Skip duplicate files
      }

      const { valid, error } = validateImageFile(file);
      if (!valid) {
        console.log(`Invalid file: ${file.name} - ${error}`);
        showToast({
          type: 'error',
          title: 'Eroare la încărcarea imaginilor',
          message: error ?? 'Fișier invalid.',
        });
        continue;
      }
      selected.push(file);
    }

    console.log(`Adding ${selected.length} new files to existing ${files.length} files`);
    // Append new files to existing ones
    setFiles(prevFiles => {
      const newFiles = [...prevFiles, ...selected];
      console.log(`Total files now: ${newFiles.length}`);
      return newFiles;
    });
  };

  const handleVideoChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (!canUploadVideo) {
      // Hard guard even if UI is bypassed
      setVideoFile(null);
      showToast({
        type: 'error',
        title: 'Permisiune necesară',
        message: 'Doar conturile verificate pot încărca video pentru piese.',
      });
      return;
    }

    const file = e.target.files?.[0];
    if (!file) {
      setVideoFile(null);
      return;
    }

    // Validate video file
    if (!file.type.startsWith('video/')) {
      showToast({
        type: 'error',
        title: 'Eroare la încărcarea videoului',
        message: 'Fișierul trebuie să fie un video.',
      });
      return;
    }

    // Check file size (max 100MB for videos)
    const maxSize = 100 * 1024 * 1024; // 100MB
    if (file.size > maxSize) {
      showToast({
        type: 'error',
        title: 'Eroare la încărcarea videoului',
        message: 'Videoul nu poate fi mai mare de 100MB.',
      });
      return;
    }

    // Check video duration (max 15 seconds)
    const video = document.createElement('video');
    video.preload = 'metadata';
    video.onloadedmetadata = () => {
      window.URL.revokeObjectURL(video.src);
      if (video.duration > 15) {
        showToast({
          type: 'error',
          title: 'Eroare la încărcarea videoului',
          message: 'Videoul nu poate fi mai lung de 15 secunde.',
        });
        setVideoFile(null);
      } else {
        setVideoFile(file);
      }
    };
    video.src = URL.createObjectURL(file);
  };

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!user) {
      showToast({
        type: 'error',
        title: 'Autentificare necesară',
        message: 'Trebuie să fii autentificat pentru a adăuga o piesă.',
      });
      router.push('/login');
      return;
    }

    if (!name.trim()) {
      showToast({
        type: 'error',
        title: 'Câmp obligatoriu',
        message: 'Numele piesei este obligatoriu.',
      });
      return;
    }

    // Validate price only for direct sales
    let numericPrice = 0;
    if (listingType === 'direct') {
      numericPrice = Number(price);
      if (!Number.isFinite(numericPrice) || numericPrice <= 0) {
        showToast({
          type: 'error',
          title: 'Preț invalid',
          message: 'Introdu un preț valid mai mare decât 0.',
        });
        return;
      }
    }

    if (listingType === 'auction') {
      const numericReserve = Number(reservePrice || price);
      if (!Number.isFinite(numericReserve) || numericReserve <= 0) {
        showToast({
          type: 'error',
          title: 'Preț de start invalid',
          message: 'Introdu un preț de start valid mai mare decât 0.',
        });
        return;
      }

      const numericMinAccept = Number(minAcceptPrice || numericReserve);
      if (!Number.isFinite(numericMinAccept) || numericMinAccept <= 0) {
        showToast({
          type: 'error',
          title: 'Preț minim acceptat invalid',
          message: 'Introdu un preț minim acceptat valid mai mare decât 0.',
        });
        return;
      }
      if (numericMinAccept < numericReserve) {
        showToast({
          type: 'error',
          title: 'Preț minim prea mic',
          message: 'Prețul minim acceptat trebuie să fie cel puțin egal cu prețul de start.',
        });
        return;
      }

      if (buyNowPrice) {
        const numericBuyNow = Number(buyNowPrice);
        if (!Number.isFinite(numericBuyNow) || numericBuyNow <= 0) {
          showToast({
            type: 'error',
            title: 'Preț "Cumpără acum" invalid',
            message: 'Introdu un preț "Cumpără acum" valid mai mare decât 0.',
          });
          return;
        }
        if (numericBuyNow < numericMinAccept) {
          showToast({
            type: 'error',
            title: 'Preț "Cumpără acum" prea mic',
            message: 'Prețul "Cumpără acum" trebuie să fie cel puțin egal cu prețul minim acceptat.',
          });
          return;
        }
      }

      if (!auctionDuration) {
        showToast({
          type: 'error',
          title: 'Durată licitație lipsă',
          message: 'Selectează durata licitației (3 sau 5 zile).',
        });
        return;
      }
    }

    try {
      setSubmitting(true);

      // Calculate product price
      let productPrice = numericPrice;
      if (listingType === 'auction') {
        const reserve = reservePrice ? Number(reservePrice) : (price ? Number(price) : 0);
        productPrice = reserve;
      }

      let videoUrl: string | null = null;
      if (videoFile && canUploadVideo) {
        // Upload video file
        const timestamp = Date.now();
        const filename = `${timestamp}_${videoFile.name}`;
        const path = `products/${user.uid}/videos/${filename}`;
        videoUrl = await uploadVideo(videoFile, path);
      }

      let productRef;
      if (editingProduct) {
        // Update existing product
        const { updateProduct } = await import('shared/adminService');
        await updateProduct(editingProduct.id, {
          name: name.trim(),
          description: description.trim(),
          price: productPrice,
          category: category || null,
          listingType: listingType,
          country: country || null,
          year: year ? Number(year) : null,
          era: era || null,
          metal: metal || null,
          denomination: denomination || null,
          diameter: diameter ? Number(diameter) : null,
          weight: weight ? Number(weight) : null,
          mintMark: mintLocation || null,
          rarity: rarity ? rarity as 'common' | 'uncommon' | 'rare' | 'very-rare' | 'extremely-rare' : null,
          grade: grade || null,
          // Certification fields
          hasCertification: hasCertification || false,
          certificationCompany: hasCertification ? certificationCompany as 'NGC' | 'PCGS' : null,
          certificationCode: hasCertification ? certificationCode.trim() : null,
          certificationGrade: hasCertification ? certificationGrade : null,
          // Offer settings
          acceptsOffers: acceptsOffers,
        });
        productRef = { id: editingProduct.id };
      } else {
        // Create new product with basic info first
        productRef = await addDoc(collection(db, 'products'), {
          name: name.trim(),
          description: description.trim(),
          images: [],
          video: videoUrl,
          price: productPrice,
          category: category || null,
          listingType: listingType,
          ownerId: user.uid,
          status: 'pending',
          country: country || null,
          year: year ? Number(year) : null,
          era: era || null,
          metal: metal || null,
          denomination: denomination || null,
          diameter: diameter || null,
          weight: weight || null,
          mintLocation: mintLocation || null,
          rarity: rarity ? rarity as 'common' | 'uncommon' | 'rare' | 'very-rare' | 'extremely-rare' : null,
          grade: grade || null,
          // Certification fields
          hasCertification: hasCertification || false,
          certificationCompany: hasCertification ? certificationCompany as 'NGC' | 'PCGS' : null,
          certificationCode: hasCertification ? certificationCode.trim() : null,
          certificationGrade: hasCertification ? certificationGrade : null,
          // Offer settings
          acceptsOffers: acceptsOffers,
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });

        // Upload images (collection items keep their existing image URLs)
        if (collectionItem && collectionItem.images && collectionItem.images.length > 0) {
          // If coming from collection, keep existing images.
          await updateDoc(doc(db, 'products', productRef.id), {
            images: collectionItem.images,
            imageProcessingStatus: 'done',
            imageProcessingTotal: collectionItem.images.length,
            imageProcessingDone: collectionItem.images.length,
            updatedAt: serverTimestamp(),
          });
        } else if (files.length > 0) {
          // Compress and upload images synchronously before storing in Firestore
          setCompressingImages(true);
          try {
            const imageUrls = await uploadMultipleImages(files, `products/${user.uid}`);
            await updateDoc(doc(db, 'products', productRef.id), {
              images: imageUrls,
              imageProcessingStatus: 'done',
              imageProcessingTotal: imageUrls.length,
              imageProcessingDone: imageUrls.length,
              updatedAt: serverTimestamp(),
            });
          } finally {
            setCompressingImages(false);
          }
        }
      }

      // Remove automatic collection addition - users should explicitly choose to add to collection
      // Only add to collection if not from existing collection item and not editing
      // This section has been intentionally removed to prevent automatic collection addition
  
      // Validate certification fields
      if (hasCertification) {
        if (!certificationCode.trim()) {
          showToast({
            type: 'error',
            title: 'Cod certificare lipsă',
            message: `Introdu codul de certificare pentru ${certificationCompany}.`,
          });
          return;
        }
  
        // Validate certification code format based on company
        let isValidCode = false;
        if (certificationCompany === 'NGC') {
          // NGC format: XXXXXXX-YYY (7 digits - 3 digits)
          const ngcRegex = /^\d{7}-\d{3}$/;
          isValidCode = ngcRegex.test(certificationCode.trim());
        } else if (certificationCompany === 'PCGS') {
          // PCGS format: XXXXXX.XX/XXXXXXXX (6 digits.2 digits/8 digits)
          const pcgsRegex = /^\d{6}\.\d{2}\/\d{8}$/;
          isValidCode = pcgsRegex.test(certificationCode.trim());
        }
        
        if (!isValidCode) {
          const formatExample = certificationCompany === 'NGC' ? '1234567-999' : '123456.78/12345678';
          showToast({
            type: 'error',
            title: 'Format cod certificare invalid',
            message: `Codul de certificare pentru ${certificationCompany} trebuie să fie în formatul ${formatExample}.`,
          });
          return;
        }
  
        if (!certificationGrade) {
          showToast({
            type: 'error',
            title: 'Grad certificare lipsă',
            message: `Selectează gradul pentru certificarea ${certificationCompany}.`,
          });
          return;
        }
      }
  
      // Only create auction if not editing (editing auctions not supported yet)
      if (listingType === 'auction' && !editingProduct) {
        const reserve = reservePrice ? Number(reservePrice) : numericPrice;
        const minAccept = minAcceptPrice ? Number(minAcceptPrice) : reserve;
        const buyNow = buyNowPrice ? Number(buyNowPrice) : null;
        const end = new Date(Date.now() + auctionDuration * 24 * 60 * 60 * 1000);
        await addDoc(collection(db, 'auctions'), {
          productId: productRef.id,
          ownerId: user.uid,
          startTime: Timestamp.fromDate(new Date()),
          endTime: Timestamp.fromDate(end),
          reservePrice: reserve,
          minAcceptPrice: minAccept,
          buyNowPrice: buyNow,
          buyNowUsed: false,
          currentBid: null,
          currentBidderId: null,
          status: 'pending',
          createdAt: serverTimestamp(),
          updatedAt: serverTimestamp(),
        });
      }

      // Update collection item if it was from collection - mark as pending approval
      if (collectionItem && user?.uid) {
        try {
          await updateCollectionItem(user.uid, collectionItem.id, {
            tags: [...(collectionItem.tags || []), listingType === 'auction' ? 'auction-pending' : 'sale-pending'],
            // Add reference to the pending product
            ...(listingType === 'auction' ? { auctionPendingId: productRef.id } : { salePendingId: productRef.id }),
          } as any);
        } catch (error) {
          console.error('Failed to update collection item:', error);
          // Don't fail the whole process for this
        }
      }

      showToast({
        type: 'success',
        title: editingProduct
          ? 'Piesă actualizată cu succes'
          : listingType === 'auction'
          ? 'Licitație trimisă spre aprobare'
          : 'Piesă trimisă spre aprobare',
        message: editingProduct
          ? 'Modificările au fost salvate.'
          : listingType === 'auction'
          ? 'Licitația a fost trimisă spre aprobare. Piesa este acum vizibilă, dar licitația va fi activată după verificare.'
          : 'Piesa a fost trimisă spre aprobare. Un administrator o va verifica înainte să apară public.',
      });

      router.push('/dashboard');
    } catch (err: any) {
      console.error('Failed to create product/auction', err);
      showToast({
        type: 'error',
        title: 'Eroare la salvare',
        message: err?.message || 'A apărut o eroare la salvarea piesei.',
      });
    } finally {
      setSubmitting(false);
    }
  };

  if (loading || !user || loadingCollectionItem) {
    return (
      <div className="container mx-auto px-4 py-8">
        <div className="flex justify-center items-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gold-500" />
          <p className="ml-4 text-slate-300">
            {loadingCollectionItem ? 'Se încarcă piesa din colecție...' : 'Se verifică sesiunea de utilizator...'}
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      <div className="max-w-2xl mx-auto bg-navy-900/80 border border-gold-500/40 rounded-2xl p-6 shadow-[0_18px_55px_rgba(0,0,0,0.85)]">
        <h1 className="text-2xl font-bold text-white mb-4">
          {editingProduct ? 'Editează piesă' : 'Adaugă o piesă'}
        </h1>
        
        {/* Toggle for Romanian Coins */}
        <div className="mb-6 p-4 bg-navy-800/50 rounded-lg border border-gold-500/20">
          <label className="flex items-center cursor-pointer">
            <input
              type="checkbox"
              checked={useAutocomplete && country === 'România'}
              onChange={(e) => {
                setUseAutocomplete(e.target.checked);
                if (e.target.checked) {
                  setCountry('România');
                } else {
                  resetAutocomplete();
                }
              }}
              className="w-4 h-4 text-gold-500 bg-navy-700 border-gold-500/40 rounded focus:ring-gold-500/50"
            />
            <span className="ml-3 text-sm text-slate-200">
              Folosește asistentul pentru monede românești
            </span>
          </label>
          <p className="mt-2 text-xs text-slate-400">
            Activează pentru auto-completare bazată pe baza de date de monede românești
          </p>
        </div>

        {/* Romanian Coin Autocomplete Section */}
        {useAutocomplete && country === 'România' && (
          <div className="mb-6 p-4 bg-gradient-to-r from-gold-500/10 to-gold-600/10 rounded-lg border border-gold-500/30 space-y-4">
            <h3 className="text-lg font-semibold text-gold-400 mb-3">🪙 Asistent Monede Românești</h3>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Denomination Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Valoare nominală *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={selectedDenomination}
                  onChange={(e) => setSelectedDenomination(e.target.value)}
                >
                  <option value="">Selectează valoarea</option>
                  {availableDenominations.map((denomination) => (
                    <option key={denomination} value={denomination}>{denomination}</option>
                  ))}
                </select>
              </div>

              {/* Year Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  An *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
                  value={selectedYear}
                  onChange={(e) => setSelectedYear(e.target.value)}
                  disabled={!selectedDenomination}
                >
                  <option value="">Selectează anul</option>
                  {availableYears.map((year) => (
                    <option key={year} value={year}>{year}</option>
                  ))}
                </select>
              </div>

              {/* Mint Selection */}
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Monetărie / Temă *
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none disabled:opacity-50 disabled:cursor-not-allowed"
                  value={selectedMint}
                  onChange={(e) => setSelectedMint(e.target.value)}
                  disabled={!selectedYear}
                >
                  <option value="">Selectează monetăria</option>
                  {availableMints.map((mint) => (
                    <option key={mint} value={mint}>{mint}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Matched Coin Preview */}
            {matchedCoin && (
              <div className="mt-4 p-3 bg-navy-800/60 rounded-lg border border-gold-500/20">
                <div className="flex items-center mb-2">
                  <svg className="w-5 h-5 text-green-400 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0zm-8-3a1 1 0 11-2 0 1 1 0 012 0zm0 8a1 1 0 100-2 1 1 0 000 2z" />
                  </svg>
                  <span className="text-sm font-semibold text-green-400">Monedă găsită în baza de date!</span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-xs text-slate-300">
                  <div><span className="text-slate-400">Diametru:</span> {matchedCoin.diameter}</div>
                  <div><span className="text-slate-400">Greutate:</span> {matchedCoin.weight}</div>
                  <div><span className="text-slate-400">Metal:</span> {matchedCoin.metal}</div>
                  <div><span className="text-slate-400">Monetărie:</span> {matchedCoin.mint_or_theme}</div>
                </div>
              </div>
            )}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Listing Type Selection */}
          <div className="mb-6">
            <label className="block text-sm font-medium text-slate-200 mb-3">
              Tip vânzare *
            </label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <label className={`relative cursor-pointer rounded-lg border-2 p-4 transition-all ${
                listingType === 'direct'
                  ? 'border-gold-400 bg-gold-400/10 text-gold-300'
                  : 'border-gold-500/40 bg-navy-800/50 text-slate-300 hover:border-gold-500/60'
              }`}>
                <input
                  type="radio"
                  name="listingType"
                  value="direct"
                  checked={listingType === 'direct'}
                  onChange={(e) => setListingType(e.target.value as 'direct' | 'auction')}
                  className="sr-only"
                />
                <div className="text-center">
                  <div className={`w-12 h-12 mx-auto mb-2 rounded-full flex items-center justify-center ${
                    listingType === 'direct' ? 'bg-navy-700 text-gold-400' : 'bg-gold-400 text-navy-900'
                  }`}>
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1" />
                    </svg>
                  </div>
                  <h3 className="font-semibold text-lg mb-1">Vând direct</h3>
                  <p className="text-sm opacity-80">Preț fix, cumpărare imediată</p>
                </div>
              </label>

              <label className={`relative cursor-pointer rounded-lg border-2 p-4 transition-all ${
                listingType === 'auction'
                  ? 'border-gold-400 bg-gold-400/10 text-gold-300'
                  : 'border-gold-500/40 bg-navy-800/50 text-slate-300 hover:border-gold-500/60'
              }`}>
                <input
                  type="radio"
                  name="listingType"
                  value="auction"
                  checked={listingType === 'auction'}
                  onChange={(e) => setListingType(e.target.value as 'direct' | 'auction')}
                  className="sr-only"
                />
                <div className="text-center">
                  <div className={`w-12 h-12 mx-auto mb-2 rounded-full flex items-center justify-center ${
                    listingType === 'auction' ? 'bg-navy-700 text-gold-400' : 'bg-gold-400 text-navy-900'
                  }`}>
                    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
                    </svg>
                  </div>
                  <h3 className="font-semibold text-lg mb-1">Pun la licitație</h3>
                  <p className="text-sm opacity-80">Licitație cu mai mulți participanți</p>
                </div>
              </label>
            </div>
          </div>

          {/* Category Selection */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Categorie *
            </label>
            <select
              className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
            >
              {CATEGORIES.map(c => (
                <option key={c} value={c}>{c}</option>
              ))}
            </select>
          </div>

          {/* Name Input */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Nume piesă *
            </label>
            <input
              type="text"
              className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
              value={name}
              onChange={(e) => {
                setName(e.target.value);
                setIsNameAutoGenerated(false);
              }}
              placeholder={matchedCoin ? `Ex: ${matchedCoin.face_value} ${matchedCoin.issue_year}` : ''}
              required
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
             {/* Price - only show for direct sales */}
             {listingType === 'direct' && (
               <div>
                 <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț fix (EUR) *
                 </label>
                 <input
                   type="number"
                   min="0"
                   step="0.01"
                   className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                   value={price}
                   onChange={(e) => setPrice(e.target.value)}
                   required
                 />
               </div>
             )}

            {/* Country */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Țara *
              </label>
              <select
                className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                value={country}
                onChange={(e) => {
                  setCountry(e.target.value);
                  if (e.target.value !== 'România') {
                    setUseAutocomplete(false);
                    resetAutocomplete();
                  }
                }}
              >
                <option value="">Selectează țara</option>
                {COUNTRIES.map(c => (
                  <option key={c} value={c}>{c}</option>
                ))}
              </select>
            </div>

            {/* Year (Manual or Auto-filled) */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                An {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
              </label>
              <input
                type="number"
                min="0"
                max="2100"
                className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                value={year}
                onChange={(e) => setYear(e.target.value)}
                placeholder="Ex: 2024"
                readOnly={!!matchedCoin && useAutocomplete}
              />
            </div>

            {/* Era - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Epocă {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={era}
                  onChange={(e) => setEra(e.target.value)}
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Metal - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Metal {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={metal}
                  onChange={(e) => setMetal(e.target.value)}
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Denomination - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Denominație {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={denomination}
                  onChange={(e) => setDenomination(e.target.value)}
                  placeholder="Ex: 1 Leu"
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Diameter - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Diametru {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={diameter}
                  onChange={(e) => setDiameter(e.target.value)}
                  placeholder="Ex: 23 mm"
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Weight - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Greutate {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={weight}
                  onChange={(e) => setWeight(e.target.value)}
                  placeholder="Ex: 5 g"
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Mint Location - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Monetărie / Temă {matchedCoin && <span className="text-xs text-green-400">(auto-completat)</span>}
                </label>
                <input
                  type="text"
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
                  value={mintLocation}
                  onChange={(e) => setMintLocation(e.target.value)}
                  placeholder="Ex: Bucharest"
                  readOnly={!!matchedCoin && useAutocomplete}
                />
              </div>
            )}

            {/* Rarity - Show for both coins and banknotes */}
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Raritate
              </label>
              <select
                className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                value={rarity}
                onChange={(e) => setRarity(e.target.value)}
              >
                <option value="">Selectează raritatea</option>
                {RARITIES.map(r => (
                  <option key={r.value} value={r.value}>{r.label}</option>
                ))}
              </select>
            </div>

            {/* Grade - Only show for coins */}
            {category === 'Monede' && (
              <div>
                <label className="block text-sm font-medium text-slate-200 mb-1">
                  Grad / stare
                </label>
                <select
                  className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                  value={grade}
                  onChange={(e) => setGrade(e.target.value)}
                >
                  <option value="">Selectează gradul</option>
                  {GRADES.map(g => (
                    <option key={g} value={g}>{g}</option>
                  ))}
                </select>
              </div>
            )}
          </div>

          {/* Alte informatii (moved from earlier position) */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Alte informații (opțional)
            </label>
            <textarea
              className="w-full rounded-lg border border-gold-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none"
              rows={4}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
            />
          </div>

          {/* Certification Section */}
          <div className="mb-6 p-4 bg-gradient-to-r from-blue-500/10 to-blue-600/10 rounded-lg border border-blue-500/30">
            <div className="flex items-center mb-4">
              <input
                type="checkbox"
                id="certification"
                checked={hasCertification}
                onChange={(e) => {
                  setHasCertification(e.target.checked);
                  if (!e.target.checked) {
                    setCertificationCode('');
                    setCertificationGrade('');
                  }
                }}
                className="w-4 h-4 text-blue-500 bg-navy-700 border-blue-500/40 rounded focus:ring-blue-500/50"
              />
              <label htmlFor="certification" className="ml-3 text-sm font-semibold text-blue-400">
                Am certificare profesională
              </label>
            </div>
            <p className="text-xs text-slate-400 mb-4">
              Bifează această opțiune dacă piesa este certificată de o companie de certificare recunoscută (NGC sau PCGS). 
              Piesele certificate sunt încapsulate și însoțite de un cod unic de autentificare.
            </p>

            {hasCertification && (
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Companie certificare *
                  </label>
                  <select
                    value={certificationCompany}
                    onChange={(e) => {
                      setCertificationCompany(e.target.value);
                      setCertificationGrade(''); // Reset grade when company changes
                    }}
                    className="w-full rounded-lg border border-blue-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                  >
                    {CERTIFICATION_COMPANIES.map(company => (
                      <option key={company.value} value={company.value}>{company.label}</option>
                    ))}
                  </select>
                </div>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-slate-200 mb-1">
                      Cod certificare *
                    </label>
                    <input
                      type="text"
                      value={certificationCode}
                      onChange={(e) => setCertificationCode(e.target.value)}
                      placeholder={certificationCompany === 'NGC' ? 'Ex: 1234567-999' : 'Ex: 123456.78/12345678'}
                      className="w-full rounded-lg border border-blue-500/40 bg-navy-800/80 px-3 py-2 text-sm text-white focus:border-blue-400 focus:outline-none"
                      required={hasCertification}
                    />
                    <p className="text-xs text-slate-400 mt-1">
                      {certificationCompany === 'NGC' 
                        ? 'Format: XXXXXXX-YYY (7 cifre - 3 cifre)'
                        : 'Format: XXXXXX.XX/XXXXXXXX (6 cifre.2 cifre/8 cifre)'}
                    </p>
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-200 mb-1">
                      Grad certificare *
                    </label>
                    <select
                      value={certificationGrade}
                      onChange={(e) => setCertificationGrade(e.target.value)}
                      className="w-full rounded-lg border border-blue-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-blue-400 focus:outline-none focus:ring-2 focus:ring-blue-500/20 [&>option]:bg-navy-900 [&>option]:text-white [&>option]:backdrop-blur-sm"
                      required={hasCertification}
                    >
                      <option value="">Selectează gradul</option>
                      {(certificationCompany === 'NGC' ? NGC_GRADES : PCGS_GRADES).map(grade => (
                        <option key={grade} value={grade}>{grade}</option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            )}
          </div>

          {/* Offer Settings Section */}
          <div className="mb-6 p-4 bg-gradient-to-r from-green-500/10 to-green-600/10 rounded-lg border border-green-500/30">
            <div className="flex items-center mb-4">
              <input
                type="checkbox"
                id="acceptsOffers"
                checked={acceptsOffers}
                onChange={(e) => setAcceptsOffers(e.target.checked)}
                className="w-4 h-4 text-green-500 bg-navy-700 border-green-500/40 rounded focus:ring-green-500/50"
              />
              <label htmlFor="acceptsOffers" className="ml-3 text-sm font-semibold text-green-400">
                Accept ofertă de la cumpărători
              </label>
            </div>
            <p className="text-xs text-slate-400">
              Bifează această opțiune dacă dorești să primești oferte de la cumpărători interesați de piesa ta. 
              Ofertele vor fi trimise prin notificări și vei putea să le accepti sau să le respingi.
            </p>
          </div>

          {/* Images - only show if not from collection */}
          {!collectionItem && (
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Imagini
              </label>
              <input
                type="file"
                multiple
                accept="image/*"
                onChange={handleFileChange}
                className="block w-full text-sm text-slate-200 file:mr-3 file:rounded-full file:border-0 file:bg-gold-500 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-navy-900 hover:file:bg-gold-400"
              />
              <p className="mt-1 text-xs text-slate-400">
                Selectează imagini din galerie sau folosește camera pentru fotografii noi
              </p>
              {files.length > 0 && (
                <>
                  <p className="mt-1 text-xs text-slate-300">
                    {files.length} imagine{files.length > 1 ? 'i' : ''} selectate
                  </p>
                  <div className="mt-2 grid grid-cols-2 md:grid-cols-4 gap-2">
                    {files.map((file, index) => (
                      <div key={`${file.name}-${file.size}-${index}`} className="relative">
                        <img
                          src={URL.createObjectURL(file)}
                          alt={`Imagine ${index + 1}`}
                          className="w-full h-20 object-cover rounded-lg border border-gold-500/30"
                        />
                        <button
                          type="button"
                          onClick={() => {
                            setFiles(prevFiles => prevFiles.filter((_, i) => i !== index));
                          }}
                          className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs hover:bg-red-600"
                        >
                          ×
                        </button>
                      </div>
                    ))}
                  </div>
                </>
              )}
            </div>
          )}

          {/* Show existing images from collection */}
          {collectionItem && collectionItem.images && collectionItem.images.length > 0 && (
            <div>
              <label className="block text-sm font-medium text-slate-200 mb-1">
                Imagini din colecție
              </label>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
                {collectionItem.images.map((image, index) => (
                  <img
                    key={index}
                    src={image}
                    alt={`Imagine ${index + 1}`}
                    className="w-full h-20 object-cover rounded-lg border border-gold-500/30"
                  />
                ))}
              </div>
              <p className="mt-1 text-xs text-slate-400">
                Se vor folosi imaginile existente din colecție
              </p>
            </div>
          )}

          {/* Video */}
          <div>
            <label className="block text-sm font-medium text-slate-200 mb-1">
              Video (opțional, max 15 secunde)
            </label>
            {canUploadVideo ? (
              <>
                <input
                  type="file"
                  accept="video/*"
                  onChange={handleVideoChange}
                  className="block w-full text-sm text-slate-200 file:mr-3 file:rounded-full file:border-0 file:bg-red-500 file:px-4 file:py-2 file:text-sm file:font-semibold file:text-white hover:file:bg-red-400"
                />
                <p className="mt-1 text-xs text-slate-400">
                  Încarcă un video scurt (max 15 secunde) din bibliotecă sau direct de la cameră pentru a demonstra piesa.
                </p>
                {videoFile && (
                  <p className="mt-1 text-xs text-green-400">
                    Video selectat: {videoFile.name}
                  </p>
                )}
              </>
            ) : (
              <p className="mt-1 text-xs text-slate-400">
                Pentru a încărca un video de prezentare, contul tău trebuie să fie <span className="text-gold-300 font-semibold">verificat</span>.
              </p>
            )}
          </div>

          {/* Auction fields (if applicable) */}
          {listingType === 'auction' && (
            <div className="mt-4 border-t border-gold-500/30 pt-4 space-y-3">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț de start licitație (EUR)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={reservePrice}
                    onChange={(e) => setReservePrice(e.target.value)}
                    placeholder={price || 'Ex: 10.00'}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț minim acceptat (doar pentru tine) (EUR)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={minAcceptPrice}
                    onChange={(e) => setMinAcceptPrice(e.target.value)}
                    placeholder={reservePrice || price || 'Ex: 100.00'}
                  />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-1">
                    Preț "Cumpără acum" (EUR, opțional)
                  </label>
                  <input
                    type="number"
                    min="0"
                    step="0.01"
                    className="w-full rounded-lg border border-gold-500/40 bg-navy-900/90 px-3 py-2 text-sm text-white focus:border-gold-400 focus:outline-none focus:ring-2 focus:ring-gold-500/20"
                    value={buyNowPrice}
                    onChange={(e) => setBuyNowPrice(e.target.value)}
                    placeholder={minAcceptPrice || reservePrice || price || 'Ex: 150.00'}
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-200 mb-3">
                    Durată licitație *
                  </label>
                  <div className="space-y-2">
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="auctionDuration"
                        value={3}
                        checked={auctionDuration === 3}
                        onChange={(e) => setAuctionDuration(Number(e.target.value))}
                        className="w-4 h-4 text-gold-500 bg-navy-700 border-gold-500/40 rounded focus:ring-gold-500/50"
                      />
                      <span className="ml-3 text-sm text-slate-200">3 zile</span>
                    </label>
                    <label className="flex items-center">
                      <input
                        type="radio"
                        name="auctionDuration"
                        value={5}
                        checked={auctionDuration === 5}
                        onChange={(e) => setAuctionDuration(Number(e.target.value))}
                        className="w-4 h-4 text-gold-500 bg-navy-700 border-gold-500/40 rounded focus:ring-gold-500/50"
                      />
                      <span className="ml-3 text-sm text-slate-200">5 zile</span>
                    </label>
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* Submit Button */}
          <div className="pt-2 flex justify-end">
            <button
              type="submit"
              disabled={submitting || compressingImages}
              className="inline-flex items-center justify-center rounded-full bg-[#e7b73c] px-6 py-2 text-sm font-semibold text-[#000940] shadow-lg shadow-[0_0_25px_rgba(231,183,60,0.7)] transition hover:bg-[#f0c955] disabled:opacity-60 disabled:cursor-not-allowed"
            >
              {submitting ? 'Se salvează...' : compressingImages ? 'Se încarcă imaginile...' : editingProduct ? 'Salvează modificările' : 'Trimite spre aprobare'}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

export default function NewProductPage() {
  return (
    <Suspense
      fallback={
        <div className="container mx-auto px-4 py-8">
          <div className="flex justify-center items-center h-64">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-gold-500" />
            <p className="ml-4 text-slate-300">Se încarcă formularul de adăugare piesă...</p>
          </div>
        </div>
      }
    >
      <NewProductPageContent />
    </Suspense>
  );
}
